Add vulnerability scan section to harbor docs
stfc/cloud-docs pull request #45
Opened 2021-02-22 14:05 UTC by apdibbo

2021-02-22 14:30 UTC, DavidFair requested changes
Some minor typos and clarifications, otherwise looks good

2021-02-22 14:30 UTC, DavidFair commented on source/ImproveTheDocs.rst
> +The following assumes you are using Windows Subsystem for Linux with Ubuntu 20.04 LTS with GitHub Desktop to manage interaction with GitHub.
Could we tweak it to
`you are using Ubuntu 18.04 or 20.04 through Windows Subsystem for Linux or natively`

2021-02-22 14:30 UTC, DavidFair commented on source/ImproveTheDocs.rst
> +Once you are happy with your changes, commit the changes and publish and then create a pull request for us to review.
Could we append `If your struggling feel free to open a PR with your changes so far and we'll be glad to provide assistance.`

2021-02-22 14:30 UTC, DavidFair commented on source/Reference/Harbor.rst
> +By default we configure all projects to automatically can images pushed to harbor for vulnerabilities and we also conduct weekly scans against all images.
Typo `can images pushed` -> `scan images pushed`

2021-02-22 14:30 UTC, DavidFair commented on source/Reference/Harbor.rst
> +You can hover over the Vulnerabilities field to view a summary or click into the artifact to view further private_repo_details
`further private_repo_details` This feels like a typo?

2021-02-22 14:30 UTC, DavidFair commented on source/Reference/Harbor.rst
> +You (if you are an administrator of the project) can configure the project to disallow pulling of images based on the vulnerabilities against the image.
`You (if you are an administrator of the project)` -> `Project Administrators can configure`

2021-02-22 14:41 UTC, apdibbo commented on source/Reference/Harbor.rst
> +By default we configure all projects to automatically can images pushed to harbor for vulnerabilities and we also conduct weekly scans against all images.
Haha

2021-02-23 08:28 UTC, apdibbo commented
I've addressed your comments

2021-02-23 09:39 UTC, DavidFair approved these changes
Thanks :+1:

2021-02-23 09:39 UTC, merged