Additional docs
stfc/cloud-docs pull request #46
Opened 2021-02-23 15:34 UTC by apdibbo

Additional docs in the run up to giving a demo of Octavia
- docker nginx tutorial
- octavia quick start guide
- update on blocking automatic updates safely

2021-02-24 14:07 UTC, DavidFair requested changes
Some minor typos, sorry about the delay just seen this PR

2021-02-24 14:07 UTC, DavidFair commented on source/Octavia/QuickStart.rst
> +Unfortunately a number of the "Operating Status" fields always report "Offline" even when the
`they are online`

2021-02-24 14:07 UTC, DavidFair commented on source/Octavia/QuickStart.rst
> +You can add another Listener to this load balancer by hitting "Create Listener" and following similar steps to the above
Could we create a link, above the section you want to link to add
`.. _my_link_name:`

then to create the link
```
:ref:`my_link_name`
```

2021-02-24 14:07 UTC, DavidFair commented on source/howto/PreventAutomaticUpdates.rst
> +This is not recommended must only be done with the express written consent of the Cloud team. This can be obtained by emailing cloud-support@gridpp.rl.ac.uk
`and must only`

2021-03-08 07:56 UTC, apdibbo commented
I have addressed your comments

2021-03-08 10:09 UTC, DavidFair requested changes
One small typo, otherwise looks good to merge - thanks

2021-03-08 10:09 UTC, DavidFair commented on source/Octavia/QuickStart.rst
> +.. _create_octavia_listener
Your missing a `:`

`.. _create_octavia_listener:`

2021-03-08 13:55 UTC, apdibbo commented
Typo fixed

2021-03-08 13:57 UTC, DavidFair approved these changes

2021-03-08 13:57 UTC, merged