sync with master
stfc/cloud-docs pull request #48
Opened 2021-03-04 13:20 UTC by mtint

2021-03-04 13:37 UTC, DavidFair commented on source/howto/CreateNewImageFromUbuntuCloud.rst
> +wget -o /var/lib/libvirt/boot/bionic-mini.iso \
You need a tab indent on all the text you want in the code block to fix the waning:

```
.. code-block:: bash

  wget

2021-03-04 13:39 UTC, DavidFair commented on source/howto/CreateNewImageFromUbuntuCloud.rst
> +=============================
This should be 
```
#################################
Create New Image From Ubuntu Cloud
#################################
```

As `####` top and bottom is a page title

2021-03-04 13:39 UTC, DavidFair commented on source/howto/CreateNewImageFromUbuntuCloud.rst
> +#######
This should be just one layer like:

```
References
#########
```

Otherwise the page title is references, rather than a chapter on the page

2021-12-02 08:31 UTC, apdibbo requested changes
This is not something we want to publish on user facing docs. Would be good to have it on the internal docs though. Please remove the PR

2022-10-03 09:48 UTC, closed without merging