Add example for accessing shares
stfc/cloud-docs pull request #93
Opened 2023-02-10 15:28 UTC by meoflynn

Example method for accessing Manila shares

2023-02-13 15:52 UTC, DavidFair requested changes

2023-02-13 15:52 UTC, DavidFair commented on source/Manila/usage.rst
> +
`The kernel method is preferred as it uses significantly less CPU marshalling data through userspace`

2023-03-01 15:34 UTC, meoflynn commented
Need to remove the merge commit as it's tried to add all the changes from previous PRs into the manila-example branch before merging this PR

2023-03-01 16:04 UTC, DavidFair approved these changes

2023-03-01 16:05 UTC, merged